openapi: 3.0.3
info:
  title: OpenAPI schema for template .
components:
  schemas:
    variables:
      type: object
      required:
      - account_name
      - account_password
      - host
      properties:
        host:
          title: Host
          type: string
          description: ZStack API host
          x-walrus-ui:
            group: Basic
            order: 2
        account_name:
          title: Account Name
          type: string
          description: ZStack account name
          x-walrus-ui:
            group: Basic
            order: 3
        account_password:
          title: Account Password
          type: string
          description: ZStack account password
          format: password
          writeOnly: true
          x-walrus-ui:
            group: Basic
            order: 4
        image_name:
          title: Image Name
          type: string
          description: Name for the log server image
          default: logserver-by-terraform
          x-walrus-ui:
            group: Basic
            order: 5
        image_url:
          title: Image Url
          type: string
          description: URL to download the image from
          default: http://minio.zstack.io:9001/packer/logserver-by-packer-image-compressed.qcow2
          x-walrus-ui:
            group: Basic
            order: 6
        backup_storage_name:
          title: Backup Storage Name
          type: string
          description: Name of the backup storage to use
          default: bs
          x-walrus-ui:
            group: Basic
            order: 7
        instance_name:
          title: Instance Name
          type: string
          description: Name for the log server instance
          default: logserver_instance
          x-walrus-ui:
            group: Basic
            order: 8
        l3_network_name:
          title: L3 Network Name
          type: string
          description: Name of the L3 network to use
          default: test
          x-walrus-ui:
            group: Basic
            order: 9
        instance_offering_name:
          title: Instance Offering Name
          type: string
          description: Name of the instance offering to use
          default: min
          x-walrus-ui:
            group: Basic
            order: 10
        ssh_user:
          title: Ssh User
          type: string
          description: SSH username for remote access
          default: root
          x-walrus-ui:
            group: Basic
            order: 11
        ssh_password:
          title: Ssh Password
          type: string
          description: SSH password for remote access
          default: password
          format: password
          writeOnly: true
          x-walrus-ui:
            group: Basic
            order: 12
      x-walrus-ui:
        groupOrder:
        - Basic
