openapi: 3.0.3
info:
  title: OpenAPI schema for template .
components:
  schemas:
    variables:
      type: object
      properties:
        image_name:
          title: 镜像名
          type: string
          description: Name for the log server image
          default: logserver-by-terraform
          x-walrus-ui:
            group: Basic
            order: 2
        image_url:
          title: 镜像 Url
          type: string
          description: URL to download the image from
          default: http://minio.zstack.io:9001/packer/logserver-by-packer-image-compressed.qcow2
          x-walrus-ui:
            group: Basic
            order: 3
        backup_storage_name:
          title: 镜像服务器
          type: string
          description: Name of the backup storage to use
          default: bs
          x-walrus-ui:
            group: Basic
            order: 4
        instance_name:
          title: 云主机名称
          type: string
          description: Name for the log server instance
          default: logserver_instance
          x-walrus-ui:
            group: Basic
            order: 5
        l3_network_name:
          title: 三层网络名称
          type: string
          description: 使用公有或编排网络，确保可以ssh访问
          default: test
          x-walrus-ui:
            group: Basic
            order: 6
        instance_offering_name:
          title: 计算规格名称
          type: string
          description: Name of the instance offering to use
          default: min
          x-walrus-ui:
            group: Basic
            order: 7
        ssh_user:
          title: Ssh User
          type: string
          description: SSH username for remote access
          default: root
          readOnly: true
          x-walrus-ui:
            group: Basic
            order: 8
        ssh_password:
          title: Ssh Password
          type: string
          description: SSH password for remote access
          default: password
          format: password
          readOnly: true
          writeOnly: true
          x-walrus-ui:
            group: Basic
            order: 9
        never_stop:
          title: Never Stop
          type: boolean
          description: VM HA
          default: true
          x-walrus-ui:
            group: Basic
            order: 10
        expunge:
          title: 是否彻底删除
          type: boolean
          default: true
          x-walrus-ui:
            group: Basic
            order: 11
      x-walrus-ui:
        groupOrder:
        - Basic
